id: P9DD40C9C
initial_creation_type: input
source_metadata:
  Title: Bhavasaṅkrāntiparikathā
  Editor: Shastri, Pandit Aiswamy
  Publisher: The Adyar Library
  Place of Publication: Madras
  Year: '1938'
  Bhavasaṅkrāntiparikathā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:53:31.106678'
last_modified_at: '2022-03-08T16:53:31.106686'
